### ISSUE TITLE
Building contracts

### ISSUE THREAD

**Issue by mikedotexe** [near/sdk-docs#13]
* Building contracts
  - [x] Basic building of the contract using cargo, and explanation on why do we need RUSTFLAGS https://github.com/near/near-sdk-rs/blob/master/examples/flags.sh#L4
  - [x] Reproducible builds using https://github.com/near/near-sdk-rs/tree/master/contact-builder and why it is very important;
  - [x] Different tools, like wasm-opt, wasm-gc, etc used here: https://github.com/near/near-sdk-rs/blob/master/minifier/minify.sh

**Comment by willemneal** [comment]
See if we can get ride of `build.sh` and just use `cargo build`

**Comment by austinabell** [comment]
For this, there can be an alias that can be added to a cargo config file to handle the build command automatically. The flags can be set with what was added in https://github.com/near/near-sdk-rs/pull/543.

Do we want to encourage setting up an alias, such as `cargo wasm` or `cargo build-wasm` which does this? I personally think it would be better to have a cargo extension built out which does this but also has the functionality to do more (such as minifying contracts, copying the built wasm file somewhere, maybe even deploying the contract?)

**Comment by willemneal** [comment]
I definitely think it's worth having a custom cargo command.  Since we are already building out rust CLI, we are using cargo's plugin system as an example. As for deploying I'm still in the camp that the `runner-rs` should handle it with a user `script`, which then our CLI could detect and execute.

**Comment by austinabell** [comment]
> I definitely think it's worth having a custom cargo command. Since we are already building out rust CLI, we are using cargo's plugin system as an example. As for deploying I'm still in the camp that the `runner-rs` should handle it with a user `script`, which then our CLI could detect and execute.

I agree, was just noting that we would have the flexibility to do much more and handle custom flags like `--optimize` for example

**Comment by willemneal** [comment]
Yeah and any other custom passes for say type definitions generation.

**Comment by volovyk-s** [comment]
Tools part: https://github.com/near/sdk-docs/pull/50

**Comment by volovyk-s** [comment]
Build instructions: https://github.com/near/sdk-docs/pull/51

**Comment by volovyk-s** [comment]
Reproducible builds: https://github.com/near/sdk-docs/pull/52
