### ISSUE TITLE
Dark mode has unreadable textboxes

### ISSUE THREAD

**Issue by ChaoticTempest** [near/sdk-docs#132]
For instance, https://www.near-sdk.io/testing/workspaces-migration-guide has the following:

<img width="853" alt="Screen Shot 2022-08-11 at 3 22 27 PM" src="https://user-images.githubusercontent.com/10100885/185668692-e983319e-11bd-4269-831c-03c99b0b4305.png">

This might be a docusaurus issue, but the expected text color should be on the darker side for lighter backgrounds

**Comment by bucanero** [comment]
This issue should be fixed once the content is moved to docs.near.org . 👍  

For example, this migration guide renders correctly in dark mode here: https://docs.near.org/develop/testing/workspaces-migration
