### ISSUE TITLE
Add Algolia again

### ISSUE THREAD

**Issue by mikedotexe** [near/sdk-docs#43]
Ryan Mehta tried to get Algolia (the service that is indexing our content on the docs.near.org site) to index the HELP.md file. They didn't want to until we got our own hosting for it, and now we do

Please see how Ryan did it here:
https://github.com/algolia/docsearch-configs/pull/4094

At the bottom of the comments you'll see the ask from the Algolia peeps. This ticket is to open a PR again linking to near-sdk.io so it can be indexed and discoverable if people search on docs.near.org.

**Comment by mikedotexe** [comment]
As per our discussions of the extended sprint, bringing in a couple more tickets.

**Comment by volovyk-s** [comment]
https://www.near-sdk.io is indexed in https://docs.near.org
![image](https://user-images.githubusercontent.com/4030422/133237003-edccaa32-6649-4005-8fe5-fc9892a1b150.png)
