### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by mikedotexe** [near/sdk-docs#44]
Look how to add search to docusaurus v2 and add it, similar to how we have it on docs.near.org.

**Comment by mikedotexe** [comment]
As per our discussions of the extended sprint, bringing in a couple more tickets.

**Comment by volovyk-s** [comment]
![image](https://user-images.githubusercontent.com/4030422/132527752-96b9cba8-4c1b-42d5-8c60-a7e27ae05f20.png)
We will need to wait a bit for the API key.

**Comment by volovyk-s** [comment]
@thisisjoshford please, mention that we need this new index on your call with Algollia.

**Comment by volovyk-s** [comment]
Created an issue here: https://github.com/algolia/docsearch-configs/issues/4646

**Comment by mikedotexe** [comment]
Let's do this, then:
https://docsearch.algolia.com/docs/run-your-own/
